server:
  port: 8080

#database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/images
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

#bucket
s3:
  bucket: ${S3_BUCKETNAME}

#amazon S3
cloud:
  aws:
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
logging:
  level:
    org.hibernate.SQL: debug
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
